### ISSUE TITLE
Is the 'status' option for questions necessary?

### ISSUE THREAD

**Issue by itsrachelfish** [itsrachelfish/weightlifter#11]
The original idea was that questions could belong to specific statuses and only appear to users / judges when an application was in that specific status. However, this would make the code for displaying questions and updating applications much more complicated. I'm wondering if this feature would actually be useful in the future or should be removed.

**Comment by marcj303** [comment]
I don't think that the questions belong to specific status. The question and answer should always be visible. What might change on status is if the answer can be edited.

**Comment by itsrachelfish** [comment]
Right, my original idea was that maybe we could have a question that appears in the "submitted" status, like "How did you feel about the grant application process so far?" to get feedback from users. But this would make the code for displaying and answering questions much more complex.

Mostly I wanted to create this issue to explain my original idea behind the feature to see if you think it would be useful, or if it should be removed.

**Comment by marcj303** [comment]
I don't think we need that for a type of question. We will handle feedback in a different form.

**Comment by itsrachelfish** [comment]
Removed as of 016ba57d3fd437b94f23e2856bc3aa86feee8420
