### ISSUE TITLE
User profiles

### ISSUE THREAD

**Issue by itsrachelfish** [itsrachelfish/weightlifter#3]
Users should be able to view and edit their own profiles where they can add additional information about themselves. Real name, contact information, etc.

We'll need to figure out what information is most useful?

**Comment by marcj303** [comment]
Admins/Judges should see the following for a user. They should be able to update everything except for the submitted grants.

Legal Name
Alternate/Playa Name
Phone number
email
submitted grant(s)

**Comment by itsrachelfish** [comment]
Cool, I wasn't sure what fields would be necessary so I figured I'd ask. If you want some example code you could use, the **laravel-voldb** project has editable user profiles.

https://github.com/itsrachelfish/laravel-voldb/blob/master/laravel/app/Http/Controllers/ProfileController.php#L56-L95
https://github.com/itsrachelfish/laravel-voldb/blob/master/laravel/database/migrations/2015_12_10_230940_create_user_data_table.php

**Comment by itsrachelfish** [comment]
Issue resolved as of pull request #14
